steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/trainocat-1772522171158/notesapp/notesapp:latest, '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/trainocat-1772522171158/notesapp/notesapp:latest']
images:
  - 'us-central1-docker.pkg.dev/trainocat-1772522171158/notesapp/notesapp:latest'
